version: 2.1
orbs:
  node: circleci/node@5.0.2
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build_and_test:
    executor: node/default
    machine: true
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Install dependecies cypress
      - run:
          command: npm run postinstall
          name: Install dependecies client and server
      - run:
          command: npm run test:coverage
          name: Run tests e2e
      - run:
          command: npm run build
          name: Build client app
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - .
  # Build-Push-Image-Docker:
  #   description: Build and push image to Google Container Registry
  #   machine: true
  #   steps:
  #     - checkout
  #     - gcr/gcr-auth
  #     - gcr/build-image:
  #         image: circle-gke
  #         tag: "v2" #Change version number e.g to 'v3' when updating application
  #     - gcr/push-image:
  #         image: circle-gke
  #         tag: "v2" #Change version number e.g to 'v3' when updating application

  # deploy:
  #   description: Deploy application to Google Kubernetes Engine
  #   machine: true
  #   steps:
  #     # Install `gcloud` and `kubectl` if not already installed.
  #     - gcp-gke/install
  #     # Initialize the `gcloud` CLI.
  #     - gcp-gke/init
  #     # Update a deployment Docker image.
  #     - gcp-gke/rollout-image:
  #         deployment: circle-ci-cluster
  #         container: dominic-backend
  #         image: gcr.io/circle-ci-demo/circle-gke:v2 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - build_and_test
      # - Build-Push-Image-Docker:
      #     requires:
      #       - build
      # - deploy:
      #     requires:
      #       - Build-Push-Image-Docker