version: 2

executors:
  latest:
    docker:
      - image: cypress/browsers:node12.13.0-chrome78-ff70

jobs:
  build:
    docker:
      - image: node:12.16.2
    parallelism: 4
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run postinstall
      - run: npm run test:coverage